# -*- coding: utf-8 -*-
#
# This file is part of jsonresolver
# Copyright (C) 2015, 2016 CERN.
#
# jsonresolver is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

notifications:
  email: false

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: xS0SP3ODUsZuz+Gz14fzQPLPBGlCYUChQa1idShx/ztfVdl0GKDTfzclmHooRHIeIt9gpz3zLGQ6phyXe+TQYzqITTI6kfp/Lx42jF2e/bY0miVw5g1sTSEipcvuVqJiE4UmPolhvU/j4Kzq4PUus3gURpzypIXqEJznUPW2ypfyBsVVBL77gUZ9kFIeMr+5QUQ0Ss+z//gLuRXoZZJckX4f5Du83NE+e5w/ZuzArFk1EOzH1637O/ZZr885XPAiOcBZRIJ8Xoj/HSetNMNRW5vXfYRkJKIB10rnV6QsaF5/PJyxw+6vLfBPhTwYVkIKHc0rQkbL2uoAYym+fHG3aIrKm0EBaFZODIRsyPbTOAFaO9r1baCi/Hgrwvon8kEQwlq2TRsGzGZ4BBAk1NYur9gTc3W2a5S1Ax2hpzGO5P4KXhelWQ0KHf3oALaG3zPptJu7DLXSBgDpJbpKGN7edDclsZF825kQwvNu/4g6QLCtjqtu2IDfdVTl4gd4e15WfpSD+5znb26QKbaM4pGn6pFHVlQzA5TXaM9WdSxmu3DxKbvDG6X1vp0tl1/qiOIyCuz0kBxCSrqnuAeFfPvVbSJyoiRP26PrivusEA1ghDZ7+u7cGZsAamCG2197PwFAE5g6O7jCBKBclES2dy6BIabTVR7z/Wr5vkCMgXwGzo4=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    python: "3.6"
    repo: inveniosoftware/jsonresolver
    tags: true
